[runtime] Fix a compiler warning by using alloca instead of a variable length array.
Fixes:

    monotouch-main.m:259:28: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
      259 |         const char *managed_argv [argc + 2];
          |                                   ^~~~~~~~
    monotouch-main.m:259:28: note: function parameter 'argc' with unknown value cannot be used in a constant expression
    monotouch-main.m:252:19: note: declared here
      252 | xamarin_main (int argc, char *argv[], enum XamarinLaunchMode launch_mode)
          |                   ^
    1 error generated.
    make: *** [../mk/rules.mk:118: .libs/ios-arm64/monotouch-main-dotnet.o] Error 1